-- MySQL Script generated by MySQL Workbench
-- 08/30/15 22:56:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema compta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema compta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `compta` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `compta` ;

-- -----------------------------------------------------
-- Table `compta`.`compte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `compta`.`compte` ;

CREATE TABLE IF NOT EXISTS `compta`.`compte` (
  `id` INT NOT NULL COMMENT '',
  `commentaire` VARCHAR(500) NULL COMMENT '',
  `nom` VARCHAR(80) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compta`.`categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `compta`.`categorie` ;

CREATE TABLE IF NOT EXISTS `compta`.`categorie` (
  `id` INT NOT NULL COMMENT '',
  `nom` VARCHAR(80) NOT NULL COMMENT '',
  `prive` TINYINT(1) NOT NULL COMMENT '',
  `code` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compta`.`comptabilite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `compta`.`comptabilite` ;

CREATE TABLE IF NOT EXISTS `compta`.`comptabilite` (
  `id` INT NOT NULL COMMENT '',
  `date` INT NOT NULL COMMENT '',
  `banque` VARCHAR(80) NOT NULL COMMENT '',
  `description_prive` VARCHAR(500) NULL COMMENT '',
  `description_declaration` VARCHAR(500) NULL COMMENT '',
  `montant` DOUBLE NOT NULL COMMENT '',
  `categorie_prive` INT NOT NULL COMMENT '',
  `categorie_declaration` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `categorie_prive`, `categorie_declaration`)  COMMENT '',
  INDEX `fk_comptabilite_categorie_idx` (`categorie_prive` ASC)  COMMENT '',
  INDEX `fk_comptabilite_categorie1_idx` (`categorie_declaration` ASC)  COMMENT '',
  CONSTRAINT `fk_comptabilite_categorie`
    FOREIGN KEY (`categorie_prive`)
    REFERENCES `compta`.`categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comptabilite_categorie1`
    FOREIGN KEY (`categorie_declaration`)
    REFERENCES `compta`.`categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
